[project]
name = "tzhsoj-assignments-checker"
version = "0.0.1"
description = "A helper to check assignments on TZHSOJ"
readme = "README"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "requests>=2.32.5",
]
